server:
  port: 8080


spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cloudstudy?serverTimezone=UTC
      username: root
      password: 1qaz2wsxE